// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using banka.models;

namespace banka.Migrations
{
    [DbContext(typeof(ApplicationConnectionDB))]
    partial class ApplicationConnectionDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("banka.models.kisi", b =>
                {
                    b.Property<int>("tc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("sifre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("tc");

                    b.ToTable("kisi");
                });
#pragma warning restore 612, 618
        }
    }
}
